テストコードを追加
soishiki/Lesson13 pull request #2
Opened 2022-11-01 08:25 UTC by soishiki

## 第13回課題
テストコードを追加

- Serviceのテスト
- Mapperのテスト
- Controllerのテスト

2022-11-02 02:27 UTC, yoshi-koyama commented
テストケース表があるとわかりやすい！

2022-11-02 02:33 UTC, yoshi-koyama commented
テストケースについてコメント
①Serviceのテストですが、ServiceにとってはHTTPステータスコードは関係なく
ID検索時にデータなしのときの確認事項は、例外が返却されるになると思います。

②これは設計次第ですが404の扱いについてです。
たとえば、
`/books/100`に該当する本のリソースが無いときには404などエラーを表すステータスで返すのが適当かと思います。
一方で、`/books?author=芥川龍之介`のように検索を意図する際にデータが無いときはレスポンスボディを空として、ステータスコードは200にするのも良いと思います。
他のWebサービスを参考にしますと、たとえばGoogle検索で一致する情報のないキーワードで検索したときには200で返ってきます。

`ｄけいｊｄｋｊ dkjfeijaejf efaijkjkejfiajg  adghaioreataljelanvlnxcv`でGoogle検索

<img width="1453" alt="スクリーンショット 2022-11-02 11 31 08" src="https://user-images.githubusercontent.com/62045457/199381538-6d48780b-94ad-4259-bba6-b8b532d07455.png">

上記は、Webページを持つものですので厳密にはRESTfulとは違いますが、ある程度参考にしていいと思います。

2022-11-02 02:34 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-11-02 02:34 UTC, YudaiNoda3576 commented on docker/docker-compose.yml
> +      # - 5050:5050 # デバッグ用
この部分は不要でしたら削除しておきましょう！

2022-11-02 02:34 UTC, YudaiNoda3576 commented on src/main/java/net/raisetechPractice/UserManagementApp/entity/User.java
> +@Setter
`User`のすべてのフィールドに対して`setter`は必要でしょうか？

2022-11-02 02:34 UTC, YudaiNoda3576 commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +                .contains(
ユーザーの件数を検証するだけでも十分な気がします！
個人的にテストコードは冗長になりがちなので、最低限の確認でも良いと考えています🙏

2022-11-02 02:34 UTC, YudaiNoda3576 commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +    // ユーザーが登録されているとき、全ユーザーのリストが返ることを確認
テストのメソッド名は日本語で記述できるので
このコメントがメソッド名になるように修正のほどよろしくお願いします🙏

2022-11-02 02:34 UTC, YudaiNoda3576 commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +        assertThat(users).isEqualTo(List.of());
usersの件数が0であることを検証すると上のテストとやっていることが統一されて理解しやすそうです！

2022-11-02 02:34 UTC, YudaiNoda3576 commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +    // 該当するユーザーが登録されているとき、該当者リストが返ることを確認
ここは分かりやすく、該当する年齢のUserが全件取得できることくらいの方が良いかもですね！

2022-11-02 02:34 UTC, YudaiNoda3576 commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +                .contains(
ここも2件取得されていることがわかれば良いかと思いますが、やるなら、年齢が25かどうか？が重要なのでそれを検証する方がわかりやすいですね！

2022-11-02 02:34 UTC, YudaiNoda3576 commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +        AssertionsForClassTypes.assertThat(actual.get()).isEqualTo(expect);
ここは取得されたUserが意図したものか？が重要なのでUserをユニークに識別するidが6かどうか？を検証すればよさそうです！

2022-11-02 02:34 UTC, YudaiNoda3576 commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +        userMapper.insertUser(form);
これはinsertした結果Userの件数が増えているかどうか？を追加で検証する必要があります！

2022-11-02 02:34 UTC, YudaiNoda3576 commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +        AssertionsForClassTypes.assertThat(actual).isEqualTo(1);
ここは元々のデータが更新されたデータに書き変わっているか？を検証するようにしましょう！

2022-11-02 02:34 UTC, YudaiNoda3576 commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +        AssertionsForClassTypes.assertThat(actual).isEqualTo(1);
ここも件数が減っていることの検証が必要ですね！

2022-11-02 02:34 UTC, YudaiNoda3576 commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +    @DataSet(value="datasets/users.yml")
こういった処理は各テストに書くと冗長なので、@BeforeEachなどを使用して共通化しても良いかと思います！

2022-11-02 02:39 UTC, yoshi-koyama commented on .github/workflows/test.yml
> +on: [push]
pull_requestもイベントに加えたほうがいいですね。
また、pushはmainブランチ時のみ実行でよいかと思います。

pull_requst: open/reopen、それからPRを作ったブランチにpush時にテスト実行
push: マージ後にテスト実行

2022-11-02 02:39 UTC, yoshi-koyama commented on src/main/java/net/raisetechPractice/UserManagementApp/entity/User.java
> +        setAge(age);
setterを使わずとも
`this.id = id;`
のようにセットすればいいと思います。

2022-11-02 02:39 UTC, yoshi-koyama commented on src/test/java/net/raisetechPractice/UserManagementApp/integrationtest/UserControllerIntegrationTest.java
> +                        + "    \"timestamp\": \"yyyy-MM-ddTHH:mm:ss.SSZ\","
![badge](https://img.shields.io/badge/review-imo-orange.svg)
ZonedDateTimeをテスト時に固定化するのもいいと思います。
`ZonedDateTime.now()`はstaticメソッドなので`mockito static`で調べると参考になる情報が出るかと思います。

2022-11-02 02:39 UTC, yoshi-koyama commented on .github/workflows/test.yml
> +      - name: Integration Test
このやり方ですとテストクラスを作るたびにCIの修正が必要ですね。
おそらく開発時にテスト追加してCI修正が漏れるということが発生しそうです。

`./gradlew test`で全件テスト実行するのはどうでしょうか？

2022-11-04 03:26 UTC, soishiki commented on docker/docker-compose.yml
> +      # - 5050:5050 # デバッグ用
特に使用していなかったため削除しました。

2022-11-04 03:28 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +                .contains(
ユーザーの件数を検証するだけに変更しました。
確かに細かいテストが多いとコードが長くなりますね。。

2022-11-04 03:28 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +    // ユーザーが登録されているとき、全ユーザーのリストが返ることを確認
テストのメソッド名を日本語にしてコメントを削除しました。

2022-11-04 03:29 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +        assertThat(users).isEqualTo(List.of());
usersの件数が0であることを検証するように修正しました。

2022-11-04 06:53 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +    // 該当するユーザーが登録されているとき、該当者リストが返ることを確認
修正した文言をメソッド名にしました。

2022-11-04 06:54 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +                .contains(
年齢が25かどうかを検証するように変更しました。

2022-11-04 06:54 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +        AssertionsForClassTypes.assertThat(actual.get()).isEqualTo(expect);
IDが6かどうかを検証するように変更しました。

2022-11-04 06:58 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +    @DataSet(value="datasets/users.yml")
@Datasetのアノテーションをテストクラスにつけると共通化できているようだったので
各メソッドのアノテーションを削除しました。

2022-11-04 06:59 UTC, soishiki commented on .github/workflows/test.yml
> +on: [push]
pushをmasterブランチのみに設定して、
pull_requestのイベントを追加しました。

2022-11-04 07:00 UTC, soishiki commented on src/main/java/net/raisetechPractice/UserManagementApp/entity/User.java
> +        setAge(age);
setterを削除して`this.id = id;`のようにセットするように修正しました。

2022-11-04 07:01 UTC, soishiki commented on .github/workflows/test.yml
> +      - name: Integration Test
`./gradlew test`で全件テスト実行するようにしました。

2022-11-04 07:02 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/integrationtest/UserControllerIntegrationTest.java
> +                        + "    \"timestamp\": \"yyyy-MM-ddTHH:mm:ss.SSZ\","
`Mockito.mockStatic`を使用してZonedDateTimeを固定化してみました。

2022-11-04 07:05 UTC, soishiki commented on src/main/java/net/raisetechPractice/UserManagementApp/entity/User.java
> +@Setter
setterは不要になったので削除しました。

こちらはテスト時のインスタンス作成で必要かと思い追加したものでしたが、
小山さんのご指摘通り、setterを使わずに`this.id = id;`のようにセットできましたね。。
https://github.com/soishiki/Lesson13/pull/2#discussion_r1011093981

2022-11-04 07:29 UTC, soishiki commented
@yoshi-koyama
コメントありがとうございます！

> テストケースについてコメント
> ①Serviceのテストですが、ServiceにとってはHTTPステータスコードは関係なく
> ID検索時にデータなしのときの確認事項は、例外が返却されるになると思います。

Serviceのテスト内容を、ステータスコードには注目せず例外が返却されること、としてみました。

> ②これは設計次第ですが404の扱いについてです。

ご指摘いただいた方向性で修正してみました。

自分なりにも調べてみましたが、
「リソースがそもそも存在していないもの」が404、
「リソース自体は存在するものの条件にあてはまるものは0件」が200
のような意味合いの違いがあるようでしたので、切り分けられようにした方が親切なのかなと思いました。

TwitterのAPIでも、
ツイート取得の`statuses/show/:id`で存在しないツイートIDを指定すると404
ツイート検索の`search/tweets`で検索結果が0件の場合は200を返しているようですね。

`/users?age=35`のようなリソースはあるものの検索結果が0件のものは
例外を出すのではなく空のリストを返すようにしてみました。

2022-11-04 07:46 UTC, YudaiNoda3576 commented on src/main/java/net/raisetechPractice/UserManagementApp/entity/User.java
> +@Setter
ですね！
基本的にコンストラクタでセットできるようにして外部から変更できないようにする構成が安パイです！

2022-11-04 07:48 UTC, YudaiNoda3576 commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +                .contains(
そうですね！
細かい検証が必要な場合もあるのですが（例えば購入処理などロジックが絡む＆正確な処理出ないと致命的なトラブルになる場合）、今回はそういうケースではないので簡易的な検証でも十分で、ユーザーの情報が合っているかどうかはテストケースの観点的にも重要ではないから不要と言うことになりそうです！

2022-11-04 07:48 UTC, YudaiNoda3576 commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +    // ユーザーが登録されているとき、全ユーザーのリストが返ることを確認
対応したコミットのURLなども一緒に添付頂けますと大変嬉しいです！！！

2022-11-04 07:54 UTC, yoshi-koyama commented
> Serviceのテスト内容を、ステータスコードには注目せず例外が返却されること、としてみました。

問題ないです 👍 

> 「リソースがそもそも存在していないもの」が404、
「リソース自体は存在するものの条件にあてはまるものは0件」が200
のような意味合いの違いがあるようでしたので、切り分ける方がよいのかなと思いました。

いいと思います！
ステータスコードをどうするかはチームやプロジェクトの設計方針次第ですね。
わたしもなかしきさんの方針で良いと思います。

Twitterの方の調査もありがとうございます！
欲を言うとドキュメントやもしリクエストを試してみたのであればそのときのcurlなどあるとより安心します！
とはいえ、調査能力が高くて素晴らしいです。

2022-11-04 07:55 UTC, yoshi-koyama commented on .github/workflows/test.yml
> +on: [push]
ありがとうございます！
ちなみに昨今のポリコレの流れでGitHubはmainブランチをdefaultブランチにするように推奨しています。

2022-11-04 08:10 UTC, yoshi-koyama commented on .github/workflows/test.yml
> +        run: docker exec spring microdnf install findutils
もしかしてこれの対応かも？
https://teratail.com/questions/q2cqw5zi4l49me

2022-11-04 08:10 UTC, yoshi-koyama commented on .github/workflows/test.yml
> +        run: docker compose -f ./docker/docker-compose.yml up -d
↑こちらですが、考えた上でdockerディレクトリを切っていると思うので対応不要です。

2022-11-04 08:10 UTC, yoshi-koyama commented on .github/workflows/test.yml
> +        run: docker rm -f mysql
docker compose downではだめですか？
また、乱暴に思えるかと思いますが、環境ごと破棄されるはずなのでコンテナの削除は不要です。

2022-11-04 08:10 UTC, yoshi-koyama commented on README.md
> +grant all on user_management_app.* to 'ユーザー名'@'localhost';
アプリケーション用のユーザー作るの good 👍 
素晴らしい観点。

2022-11-04 08:10 UTC, yoshi-koyama commented on src/test/java/net/raisetechPractice/UserManagementApp/service/UserServiceImplTest.java
> +        assertThat(true).isEqualTo(true);
これは意味のない検証になっていますね。

2022-11-04 08:10 UTC, yoshi-koyama commented on src/test/java/net/raisetechPractice/UserManagementApp/service/UserServiceImplTest.java
> +        when(userMapper.findUsers(null)).thenReturn(List.of());
`Collections.emptyList()`を使うのが適切ですね。
```suggestion
        when(userMapper.findUsers(null)).thenReturn(Collections.emptyList());
```

2022-11-04 08:10 UTC, yoshi-koyama commented on src/test/java/net/raisetechPractice/UserManagementApp/service/UserServiceImplTest.java
> +    public void Userが全件取得できること() throws Exception {
Given-When-ThenでいうところのWhenが抜けていますね。
```suggestion
    public void 引数にnullをわたしたときにUserが全件取得できること() throws Exception {
```

2022-11-04 08:10 UTC, yoshi-koyama commented on src/test/java/net/raisetechPractice/UserManagementApp/service/UserServiceImplTest.java
> +        when(userMapper.findUserById(1)).thenReturn(Optional.ofNullable(null));
`Optional.empty()`を使うのがより適切ですね。
```suggestion
        when(userMapper.findUserById(1)).thenReturn(Optional.empty());
```

2022-11-04 08:10 UTC, yoshi-koyama commented on src/test/java/net/raisetechPractice/UserManagementApp/service/UserServiceImplTest.java
> +        assertThat(true).isEqualTo(true);
こちら意味のない検証になっていますね。

2022-11-07 03:44 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +    // ユーザーが登録されているとき、全ユーザーのリストが返ることを確認
すみません、ほかの修正とごっちゃになってしまっているのですが、
こちらのコミットで対応しました。。
https://github.com/soishiki/Lesson13/pull/2/commits/3f9e90566027ab1cad7804bf4f13badce203166c

2022-11-07 03:46 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +        userMapper.insertUser(form);
insertした後の件数が期待通りになっているか確認するようにしてみました。
https://github.com/soishiki/Lesson13/pull/2/commits/6905c3d33967f34a052d763273dd4cc47f665e1e

2022-11-07 03:46 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +        AssertionsForClassTypes.assertThat(actual).isEqualTo(1);
insertした後の件数が期待通りになっているか確認するようにしてみました。
https://github.com/soishiki/Lesson13/pull/2/commits/6905c3d33967f34a052d763273dd4cc47f665e1e

2022-11-07 03:47 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/repository/UserMapperTest.java
> +        AssertionsForClassTypes.assertThat(actual).isEqualTo(1);
updateした後のデータが期待通りになっているか確認するようにしてみました。
https://github.com/soishiki/Lesson13/pull/2/commits/cef417cf709c5ea33c7351f0f08b6f67c61e0b8e

2022-11-07 03:49 UTC, soishiki commented on .github/workflows/test.yml
> +on: [push]
mainブランチをデフォルトブランチに設定しました。
https://github.com/soishiki/Lesson13/pull/2/commits/5060deb724a701fd043d2388d4e6c569690d0866

2022-11-07 03:50 UTC, soishiki commented on .github/workflows/test.yml
> +      - name: Checkout And Build
step名を変更しました。
https://github.com/soishiki/Lesson13/pull/2/commits/5737c88aa377c6be05e697a25b676ed684b3c674

2022-11-07 03:56 UTC, soishiki commented on .github/workflows/test.yml
> +        run: docker exec spring microdnf install findutils
そうです！
Dockerで作成している実行環境にxargsコマンドが入っておらず、
gradlewのこの部分で発生したエラー対策としてコマンドをインストールしてみました。
# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

2022-11-07 04:01 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/service/UserServiceImplTest.java
> +        assertThat(true).isEqualTo(true);
こちらの検証は削除しました。
https://github.com/soishiki/Lesson13/pull/2/commits/c9f6fccb5f5405ba9b8afac8be43eea1806c888a

2022-11-07 04:02 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/service/UserServiceImplTest.java
> +        when(userMapper.findUsers(null)).thenReturn(List.of());
`Collections.emptyList()`を使うように修正しました。
https://github.com/soishiki/Lesson13/pull/2/commits/7aa2f2ddbb49b1f292eb730c8b1a7cdb5fb93d64

2022-11-07 04:02 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/service/UserServiceImplTest.java
> +    public void Userが全件取得できること() throws Exception {
メソッド名変更しました。
https://github.com/soishiki/Lesson13/pull/2/commits/0ea11c24bd0d8a5baef7e26d0eaf4ff4e88f1bd4

2022-11-07 04:03 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/service/UserServiceImplTest.java
> +        when(userMapper.findUserById(1)).thenReturn(Optional.ofNullable(null));
`Optional.empty()`を使うように修正しました。
https://github.com/soishiki/Lesson13/pull/2/commits/b9e6f4fc9d9dd5a0903eed807ab3f476f2a62871

2022-11-07 04:03 UTC, soishiki commented on src/test/java/net/raisetechPractice/UserManagementApp/service/UserServiceImplTest.java
> +        assertThat(true).isEqualTo(true);
こちらの検証は削除しました。
https://github.com/soishiki/Lesson13/pull/2/commits/c9f6fccb5f5405ba9b8afac8be43eea1806c888a

2022-11-07 04:07 UTC, soishiki commented on .github/workflows/test.yml
> +        run: docker rm -f mysql
コンテナ削除のstepを削除しました。
https://github.com/soishiki/Lesson13/pull/2/commits/79109be7151a8dedf74180a04f0c4299c2926407

2022-11-07 04:10 UTC, soishiki commented on .github/workflows/test.yml
> +        run: docker compose -f ./docker/docker-compose.yml up -d
これについては、docker関係のものは1か所にまとめておこうかな？ぐらいの意味で置いてました。。
これだとdocker compose downのときもdockerディレクトリに移動する必要があるので、
rootディレクトリ直下にあった方がシンプルかな？と思ったので修正しました。
https://github.com/soishiki/Lesson13/pull/2/commits/9a411605c4967512ecc3bc579bf5e4f4ba651d6b

2022-11-07 04:32 UTC, yoshi-koyama commented on .github/workflows/test.yml
> +        run: docker compose -f ./docker/docker-compose.yml up -d
そうですね！up/downの際に移動がちょっと面倒なのでそのほうがいいと思います！

2022-11-07 04:32 UTC, yoshi-koyama commented on .github/workflows/test.yml
> +        run: docker rm -f mysql
確認しました！

2022-11-07 04:32 UTC, yoshi-koyama commented on .github/workflows/test.yml
> +        run: docker exec spring microdnf install findutils
なるほど。承知しました mm

2022-11-07 04:34 UTC, yoshi-koyama commented on src/test/java/net/raisetechPractice/UserManagementApp/service/UserServiceImplTest.java
> +        assertThat(true).isEqualTo(true);
問題ないです！

2022-11-07 04:35 UTC, yoshi-koyama commented
コミットの単位も丁寧でいい感じ。

2022-11-07 04:45 UTC, yoshi-koyama commented on build.gradle
> +	implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.4'
![badge](https://img.shields.io/badge/review-ask-blue.svg)
jackson周りはSpring Bootを使うにあたって自然体で使えるようになるはずだと思います。

https://spring.pleiades.io/spring-boot/docs/current/reference/html/dependency-versions.html#appendix.dependency-versions

jackson-coreなどがすでに一覧にありますね。

こちら理由があって追加されたのでしょうか？
消してみて動くのであれば消したおいてほしいのと、もし追加しなければいけなかい理由があれば教えていただきたいです（私の認識誤りの可能性もありますので）。

2022-11-07 04:45 UTC, yoshi-koyama commented on src/main/java/net/raisetechPractice/UserManagementApp/controller/UserController.java
>          userList = userService.findUsers(age).stream().map(UserResponse::new).toList();
こうのように書けばよいです。
```suggestion
        List<UserResponse> userList = userService.findUsers(age).stream().map(UserResponse::new).toList();
```

2022-11-07 04:45 UTC, yoshi-koyama commented on src/test/java/net/raisetechPractice/UserManagementApp/integrationtest/UserControllerIntegrationTest.java
> +package net.raisetechPractice.UserManagementApp.integrationtest;
別PR対応で構いません。
`package net.raisetechPractice.UserManagementApp.integrationtest;`
こちらですが、Javaのパッケージ名の命名規則についてご確認いただき修正お願いしたいです。
参考：https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2022-11-07 06:09 UTC, soishiki commented on build.gradle
> +	implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.4'
この3行を消しても動作しました！
おそらくレスポンスボディのjsonをテストするときに
方法を調べて試しているうちに不要になっていたものだと思われます。。
https://github.com/soishiki/Lesson13/pull/2/commits/5b32c0ce90ee5adfb8b2a139ea886b3b9498a813

2022-11-07 06:10 UTC, soishiki commented on src/main/java/net/raisetechPractice/UserManagementApp/controller/UserController.java
>          userList = userService.findUsers(age).stream().map(UserResponse::new).toList();
変数の宣言と代入を同時に行うように修正しました。
https://github.com/soishiki/Lesson13/pull/2/commits/e8cd2e61070d655a982f07fafe94a0236d05b597

2022-11-07 06:13 UTC, soishiki commented on build.gradle
> +	implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.4'
こちら3行を消しても動きました！
おそらくレスポンスボディのjsonをテストするときに
方法を調べて試しているうちに不要になったものだと思われます。。
https://github.com/soishiki/Lesson13/pull/2/commits/5b32c0ce90ee5adfb8b2a139ea886b3b9498a813

2022-11-07 06:26 UTC, yoshi-koyama commented on build.gradle
> +	implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.4'
そういうことですね。
承知しました！

2022-11-07 08:35 UTC, YudaiNoda3576 approved these changes
![LGTM](https://images.lgtmgen.org/7d9ab8eb-248f-4047-af24-a70479d21b30)

2022-11-07 10:23 UTC, merged